name = "pastebin-worker"
main = "src/worker.js"
compatibility_date = "2025-03-01"

[[kv_namespaces]]
binding = "PASTE_KV"
id = "c22e75e9285a458ca1b8e17f60620e3a"        # aap naya KV namespace banayein
# `wrangler kv:namespace create paste-kv`

[[d1_databases]]
binding = "PASTE_DB"
database_name = "pastebin-db"
database_id = "cfk_htkwaSLQQBZn6fVgXpVbU5mf8bPn1dhijO6nWdQdc8416e94"
